name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: npm i
    - name: debugbear on /
      run: $(npm bin)/debugbear --pageId=6383 --waitForResult --baseBranch=master --inferBuildInfo
      - with:
          DEBUGBEAR_API_KEY: ${{ secrets.DEBUGBEAR_API_KEY }}
