name: CI
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm i
      - run: ./node_modules/.bin/debugbear --pageId=6383 --waitForResult --baseBranch=master --inferBuildInfo
        env:
          DEBUGBEAR_API_KEY: ${{ secrets.DEBUGBEAR_API_KEY }}
